Default: &defaults
  port: 3000
  copyright: Insert copyright statement here
  approot: ""
  #analytics: UA-YOURCODE

Development:
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  <<: *defaults

